package ml.school.controller;
import ml.school.entity.*; import ml.school.repository.*; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/eleves") class EleveController {private final EleveRepository r; EleveController(EleveRepository r){this.r=r;} @GetMapping List<Eleve> all(){return r.findAll();}@GetMapping("/{id}") Eleve one(@PathVariable Long id){return r.findById(id).orElseThrow();}@PostMapping Eleve add(@RequestBody Eleve x){return r.save(x);}@PutMapping("/{id}") Eleve edit(@PathVariable Long id,@RequestBody Eleve x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/classes") class ClasseController {private final ClasseRepository r; ClasseController(ClasseRepository r){this.r=r;} @GetMapping List<Classe> all(){return r.findAll();}@PostMapping Classe add(@RequestBody Classe x){return r.save(x);}@PutMapping("/{id}") Classe edit(@PathVariable Long id,@RequestBody Classe x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/annees-scolaires") class AnneeController {private final AnneeScolaireRepository r; AnneeController(AnneeScolaireRepository r){this.r=r;} @GetMapping List<AnneeScolaire> all(){return r.findAll();}@PostMapping AnneeScolaire add(@RequestBody AnneeScolaire x){return r.save(x);}@PutMapping("/{id}") AnneeScolaire edit(@PathVariable Long id,@RequestBody AnneeScolaire x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/parents") class ParentController {private final ParentRepository r; ParentController(ParentRepository r){this.r=r;} @GetMapping List<Parent> all(){return r.findAll();}@PostMapping Parent add(@RequestBody Parent x){return r.save(x);}@PutMapping("/{id}") Parent edit(@PathVariable Long id,@RequestBody Parent x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/enseignants") class EnseignantController {private final EnseignantRepository r; EnseignantController(EnseignantRepository r){this.r=r;} @GetMapping List<Enseignant> all(){return r.findAll();}@PostMapping Enseignant add(@RequestBody Enseignant x){return r.save(x);}@PutMapping("/{id}") Enseignant edit(@PathVariable Long id,@RequestBody Enseignant x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/matieres") class MatiereController {private final MatiereRepository r; MatiereController(MatiereRepository r){this.r=r;} @GetMapping List<Matiere> all(){return r.findAll();}@PostMapping Matiere add(@RequestBody Matiere x){return r.save(x);}@PutMapping("/{id}") Matiere edit(@PathVariable Long id,@RequestBody Matiere x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/inscriptions") class InscriptionController {private final InscriptionRepository r; InscriptionController(InscriptionRepository r){this.r=r;} @GetMapping List<Inscription> all(){return r.findAll();}@PostMapping Inscription add(@RequestBody Inscription x){return r.save(x);}@PutMapping("/{id}") Inscription edit(@PathVariable Long id,@RequestBody Inscription x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/notes") class NoteController {private final NoteRepository r; NoteController(NoteRepository r){this.r=r;} @GetMapping List<Note> all(){return r.findAll();}@PostMapping Note add(@RequestBody Note x){return r.save(x);}@PutMapping("/{id}") Note edit(@PathVariable Long id,@RequestBody Note x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/evaluations") class EvaluationController {private final EvaluationRepository r; EvaluationController(EvaluationRepository r){this.r=r;} @GetMapping List<Evaluation> all(){return r.findAll();}@PostMapping Evaluation add(@RequestBody Evaluation x){return r.save(x);}@PutMapping("/{id}") Evaluation edit(@PathVariable Long id,@RequestBody Evaluation x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/bulletins") class BulletinController {private final BulletinRepository r; BulletinController(BulletinRepository r){this.r=r;} @GetMapping List<Bulletin> all(){return r.findAll();}@PostMapping Bulletin add(@RequestBody Bulletin x){return r.save(x);}@PutMapping("/{id}") Bulletin edit(@PathVariable Long id,@RequestBody Bulletin x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/absences") class AbsenceController {private final AbsenceRepository r; AbsenceController(AbsenceRepository r){this.r=r;} @GetMapping List<Absence> all(){return r.findAll();}@PostMapping Absence add(@RequestBody Absence x){return r.save(x);}@PutMapping("/{id}") Absence edit(@PathVariable Long id,@RequestBody Absence x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/paiements") class PaiementController {private final PaiementRepository r; PaiementController(PaiementRepository r){this.r=r;} @GetMapping List<Paiement> all(){return r.findAll();}@PostMapping Paiement add(@RequestBody Paiement x){return r.save(x);}@PutMapping("/{id}") Paiement edit(@PathVariable Long id,@RequestBody Paiement x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/personnels-administratifs") class PersonnelController {private final PersonnelAdministratifRepository r; PersonnelController(PersonnelAdministratifRepository r){this.r=r;} @GetMapping List<PersonnelAdministratif> all(){return r.findAll();}@PostMapping PersonnelAdministratif add(@RequestBody PersonnelAdministratif x){return r.save(x);}@PutMapping("/{id}") PersonnelAdministratif edit(@PathVariable Long id,@RequestBody PersonnelAdministratif x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/cours") class CoursController {private final CoursRepository r; CoursController(CoursRepository r){this.r=r;} @GetMapping List<Cours> all(){return r.findAll();}@PostMapping Cours add(@RequestBody Cours x){return r.save(x);}@PutMapping("/{id}") Cours edit(@PathVariable Long id,@RequestBody Cours x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
@RestController @RequestMapping("/api/emplois-du-temps") class EmploiController {private final EmploiDuTempsRepository r; EmploiController(EmploiDuTempsRepository r){this.r=r;} @GetMapping List<EmploiDuTemps> all(){return r.findAll();}@PostMapping EmploiDuTemps add(@RequestBody EmploiDuTemps x){return r.save(x);}@PutMapping("/{id}") EmploiDuTemps edit(@PathVariable Long id,@RequestBody EmploiDuTemps x){x.setId(id);return r.save(x);}@DeleteMapping("/{id}")void del(@PathVariable Long id){r.deleteById(id);}}
